#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LLM-call wrapper for the cognitive + rhetorical humanization stages.

Provider-agnostic: works with any OpenAI-compatible chat-completions endpoint
(Moonshot, MiniMax, OpenAI, Anthropic-via-proxy, Together, Groq, on-prem, etc.).

Routes to one of two backends:
  - api    — any cloud OpenAI-compatible endpoint (configure via LLM_API_URL)
  - local  — a local OpenAI-compatible server (defaults to Ollama on 127.0.0.1)

Gracefully degrades: if the backend is unavailable or unconfigured, returns the
input unchanged with a warning so the pipeline can fall back to lex-only mode.

Prompts for each transformation pass live in the PROMPTS dict and load
context from the skill's references/ directory.

Usage (as module):
    from llm_transform import transform
    out, info = transform(text, pass_name="cognitive", backend="api")

Usage (CLI for testing):
    python llm_transform.py --input "نص هنا" --pass cognitive --backend api
"""
from __future__ import annotations
import argparse, json, sys, time, urllib.request, urllib.error
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

# ── Backend definitions ─────────────────────────────────────────────────────
# Backend URLs, models, and tokens are READ FROM ENVIRONMENT (or per-call args)
# — never hardcoded. The skill is provider-agnostic: any OpenAI-compatible
# chat-completions endpoint works.
#
# Env vars (api backend, required — set whichever your provider needs):
#   LLM_API_URL   — full chat-completions URL (no default, must be set)
#   LLM_API_KEY   — bearer token (omit if your endpoint takes no auth)
#   LLM_MODEL     — exact model identifier your provider expects
#   LLM_TIMEOUT_S — request timeout in seconds (default 300)
#
# Env vars (local backend, optional — defaults to Ollama):
#   LOCAL_API_URL   — full chat-completions URL (default: Ollama on localhost)
#   LOCAL_API_KEY   — usually unset for Ollama
#   LOCAL_MODEL     — model tag (default: qwen2.5:14b-instruct)
#   LOCAL_TIMEOUT_S — request timeout in seconds (default 300)
#
# Example provider configurations (real public endpoints + model IDs as of 2026):
#   Moonshot:  LLM_API_URL=https://api.moonshot.cn/v1/chat/completions
#              LLM_MODEL=moonshot-v1-8k   (or -32k / -128k)
#   OpenAI:    LLM_API_URL=https://api.openai.com/v1/chat/completions
#              LLM_MODEL=gpt-4o-mini
#   MiniMax:   LLM_API_URL=https://api.minimaxi.chat/v1/text/chatcompletion_v2
#              LLM_MODEL=abab6.5s-chat
#   Together:  LLM_API_URL=https://api.together.xyz/v1/chat/completions
#              LLM_MODEL=Qwen/Qwen2.5-72B-Instruct
#   Groq:      LLM_API_URL=https://api.groq.com/openai/v1/chat/completions
#              LLM_MODEL=llama-3.3-70b-versatile

import os as _os

BACKENDS = {
    "api": {
        "url": _os.environ.get("LLM_API_URL", ""),
        "model_default": _os.environ.get("LLM_MODEL", ""),
        "env_token": "LLM_API_KEY",
        "timeout_s": int(_os.environ.get("LLM_TIMEOUT_S", "300")),
    },
    "local": {
        "url": _os.environ.get("LOCAL_API_URL",
                                "http://127.0.0.1:11434/v1/chat/completions"),
        "model_default": _os.environ.get("LOCAL_MODEL", "qwen2.5:14b-instruct"),
        "env_token": "LOCAL_API_KEY",   # Optional for Ollama (usually none needed)
        "timeout_s": int(_os.environ.get("LOCAL_TIMEOUT_S", "300")),
    },
}


# ── Transformation prompts ──────────────────────────────────────────────────

def cognitive_prompt(text: str) -> str:
    """Prompt for stages 1-8 (cognitive structure + scope + transitions + partitioning)."""
    return f"""You are an expert Arabic prose editor. The text below was generated by an AI and reads flat — it has clean grammar but lacks the cognitive sophistication of human Arabic writing. Re-author it preserving the MEANING but adding:

1. **استنتاج واضح** — visible reasoning steps from premises to conclusions
2. **استدلال مرتب** — argumentation chains with classical Arabic logical connectors (إذ، حيث، بناءً عليه، يستنتج من ذلك)
3. **استنباط من العام إلى الخاص** — pulling specific insight from general claims
4. **تحديد النطاق** — explicit scope markers ("في حدود ما يخص ...", "ولا نقصد هنا ...")
5. **تدرج في الشرح** — start simple, build complexity; reader scaffolded forward
6. **انتقال أنيق بين الأفكار** — spiral coherence preferred over flat-linear (return to earlier ideas with new framing)
7. **تقسيم للمحاور** — orthogonal-axis decomposition rather than nested lists

Constraints:
- Preserve all factual content; do NOT add unsupported claims
- Stay in MSA (فصحى المعاصرة or مبسّطة); do NOT shift to dialect
- Do NOT use the word "إذن" or "بالتالي" more than once each
- Output ONLY the rewritten Arabic — no commentary, no markdown, no English

Text to humanize:

{text}

Rewritten:"""


def rhetorical_prompt(text: str) -> str:
    """Prompt for stages 9-13 (literary art + historical + imagination + rhetoric + coherence)."""
    return f"""You are an expert Arabic prose editor. The text below has acceptable structure but lacks rhetorical sophistication. Re-author preserving meaning but adding (judiciously — over-application is parody):

1. **فن أدبي** — rhythm, imagery, occasional elevated diction
2. **استدلال تاريخي** — one apt historical or event-based reference where it strengthens an argument (Andalusian, early-Islamic, Abbasid, or modern — pick what fits)
3. **تخيل وتجسيد** — one or two concrete sensory or metaphor moments where the abstract benefits from being seen
4. **بلاغة** — sparing use of: استعارة (preferred), كناية, طباق. Avoid جناس in non-literary contexts. NEVER use سجع unless the register is literary/oratorical.
5. **عدم تكرار + استدلال داخلي** — vary lexical and structural repetition; add 1-2 phrases referencing what was said earlier in the text ("كما قدّمنا"، "وفي ضوء ما تقدّم"، "إذ سبق")

Strict constraints:
- AT MOST ONE rhetorical figure per ~80 words. Density beyond this is parody.
- NO سجع outside literary register.
- If the text is technical / legal / news — preserve register; do NOT inject rhetoric.
- Preserve all factual content; do NOT add unsupported claims.
- Output ONLY the rewritten Arabic.

Text to enrich:

{text}

Rewritten:"""


def coherence_prompt(text: str) -> str:
    """Final pass — non-repetition + intra-text citation."""
    return f"""Final editorial pass on this Arabic text. Two operations:

1. **Detect and resolve repetition** — lexical repetition (same word within 4 sentences), structural repetition (same sentence-opening pattern 3+ times in a row), and semantic repetition (same idea restated without new framing). Vary the surface form; preserve meaning.

2. **Add 1-2 intra-text citation markers** — phrases that explicitly reference an earlier point in THIS text: "كما أشرنا"، "وفي ضوء ما تقدّم"، "إذ سبق أن قلنا"، "بناءً على ما أسلفنا"، "ولعل القارئ يتذكر". Only where natural — forced citation reads worse than its absence.

Output ONLY the rewritten Arabic — no commentary.

Text:

{text}

Final:"""


PROMPTS = {
    "cognitive": cognitive_prompt,
    "rhetorical": rhetorical_prompt,
    "coherence": coherence_prompt,
}


# ── Backend call ────────────────────────────────────────────────────────────

def call(backend_name: str, prompt: str, model: str | None = None,
         auth_token: str | None = None, backend_url: str | None = None) -> dict:
    """Call the chosen backend. Returns {ok, content, error, duration_s, backend}."""
    cfg = BACKENDS.get(backend_name)
    if not cfg:
        return {"ok": False, "error": f"unknown backend: {backend_name}",
                "backend": backend_name}
    url = backend_url or cfg["url"]
    model = model or cfg["model_default"]
    if not url:
        return {"ok": False, "backend": backend_name,
                "error": (f"backend '{backend_name}' has no URL configured. "
                          f"Set LLM_API_URL env var (or pass --backend-url) "
                          f"to your provider's chat-completions endpoint.")}
    if not model:
        return {"ok": False, "backend": backend_name,
                "error": (f"backend '{backend_name}' has no model configured. "
                          f"Set LLM_MODEL env var (or pass --model) to the "
                          f"exact model identifier your provider expects.")}
    token = auth_token
    if not token and cfg.get("env_token"):
        import os
        token = os.environ.get(cfg["env_token"])
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    body = json.dumps({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 4000,
        "temperature": 0.7,
    }, ensure_ascii=False).encode()
    start = time.time()
    try:
        req = urllib.request.Request(url, data=body, headers=headers)
        with urllib.request.urlopen(req, timeout=cfg["timeout_s"]) as r:
            result = json.loads(r.read())
    except urllib.error.HTTPError as e:
        return {"ok": False, "error": f"HTTP {e.code}: {e.read()[:200]!r}",
                "backend": backend_name, "duration_s": round(time.time()-start, 1)}
    except Exception as e:
        return {"ok": False, "error": f"{type(e).__name__}: {e}",
                "backend": backend_name, "duration_s": round(time.time()-start, 1)}

    try:
        content = result["choices"][0]["message"]["content"]
    except (KeyError, IndexError):
        return {"ok": False, "error": f"no content in response: {str(result)[:200]}",
                "backend": backend_name, "duration_s": round(time.time()-start, 1)}

    # Strip <think> blocks (some models emit them)
    while "<think>" in content and "</think>" in content:
        a = content.find("<think>")
        b = content.find("</think>", a) + len("</think>")
        content = (content[:a] + content[b:]).strip()
    return {"ok": True, "content": content, "backend": backend_name,
            "model": model, "duration_s": round(time.time()-start, 1)}


def transform(text: str, pass_name: str, backend: str = "api",
              auth_token: str | None = None, model: str | None = None,
              backend_url: str | None = None) -> tuple[str, dict]:
    """High-level interface used by humanize_v2.py.
    Returns (transformed_text, info). On failure, returns (original_text, info)."""
    if pass_name not in PROMPTS:
        return text, {"ok": False, "error": f"unknown pass: {pass_name}"}
    prompt = PROMPTS[pass_name](text)
    info = call(backend, prompt, model=model, auth_token=auth_token,
                backend_url=backend_url)
    info["pass"] = pass_name
    if info.get("ok"):
        return info["content"].strip(), info
    return text, info  # graceful degradation: return original


# ── CLI for testing ─────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", "-i", help="Inline text")
    ap.add_argument("--file", "-f", type=Path, help="Read text from file")
    ap.add_argument("--pass", dest="pass_", required=True,
                    choices=list(PROMPTS.keys()))
    ap.add_argument("--backend", default="api", choices=list(BACKENDS.keys()))
    ap.add_argument("--backend-url", help="Override LLM_API_URL for one invocation")
    ap.add_argument("--model", help="Override LLM_MODEL for one invocation")
    ap.add_argument("--auth-token", help="Override LLM_API_KEY for one invocation")
    ap.add_argument("--output", "-o", type=Path)
    args = ap.parse_args()

    if args.file:
        text = args.file.read_text(encoding="utf-8")
    elif args.input:
        text = args.input
    else:
        text = sys.stdin.read()
    if not text.strip():
        raise SystemExit("empty input")

    out, info = transform(text, args.pass_, backend=args.backend,
                          auth_token=args.auth_token, model=args.model,
                          backend_url=args.backend_url)
    print(f"[backend={info.get('backend')}  ok={info.get('ok')}  "
          f"duration_s={info.get('duration_s')}]", file=sys.stderr)
    if not info.get("ok"):
        print(f"[error] {info.get('error')}", file=sys.stderr)
        print("[note] returning ORIGINAL text unchanged (graceful degradation)",
              file=sys.stderr)
    if args.output:
        args.output.write_text(out, encoding="utf-8")
    else:
        print(out)


if __name__ == "__main__":
    main()
